package main

import (
	"image/color"

	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
)

func main() {
	// Plot of series of pseudorandom numbers generated by
	// function (rand() % 1000) from standard C library with seed 0.

	pointsOfFunctionPlot := make(plotter.XYs, 301)

	pointsOfFunctionPlot[0].X = 0.0
	pointsOfFunctionPlot[0].Y = 0.0

	pointsOfFunctionPlot[1].X = 0.1
	pointsOfFunctionPlot[1].Y = 383.0

	pointsOfFunctionPlot[2].X = 0.2
	pointsOfFunctionPlot[2].Y = 886.0

	pointsOfFunctionPlot[3].X = 0.3
	pointsOfFunctionPlot[3].Y = 777.0

	pointsOfFunctionPlot[4].X = 0.4
	pointsOfFunctionPlot[4].Y = 915.0

	pointsOfFunctionPlot[5].X = 0.5
	pointsOfFunctionPlot[5].Y = 793.0

	pointsOfFunctionPlot[6].X = 0.6
	pointsOfFunctionPlot[6].Y = 335.0

	pointsOfFunctionPlot[7].X = 0.7
	pointsOfFunctionPlot[7].Y = 386.0

	pointsOfFunctionPlot[8].X = 0.8
	pointsOfFunctionPlot[8].Y = 492.0

	pointsOfFunctionPlot[9].X = 0.9
	pointsOfFunctionPlot[9].Y = 649.0

	pointsOfFunctionPlot[10].X = 1.0
	pointsOfFunctionPlot[10].Y = 421.0

	pointsOfFunctionPlot[11].X = 1.1
	pointsOfFunctionPlot[11].Y = 362.0

	pointsOfFunctionPlot[12].X = 1.2
	pointsOfFunctionPlot[12].Y = 27.0

	pointsOfFunctionPlot[13].X = 1.3
	pointsOfFunctionPlot[13].Y = 690.0

	pointsOfFunctionPlot[14].X = 1.4
	pointsOfFunctionPlot[14].Y = 59.0

	pointsOfFunctionPlot[15].X = 1.5
	pointsOfFunctionPlot[15].Y = 763.0

	pointsOfFunctionPlot[16].X = 1.6
	pointsOfFunctionPlot[16].Y = 926.0

	pointsOfFunctionPlot[17].X = 1.7
	pointsOfFunctionPlot[17].Y = 540.0

	pointsOfFunctionPlot[18].X = 1.8
	pointsOfFunctionPlot[18].Y = 426.0

	pointsOfFunctionPlot[19].X = 1.9
	pointsOfFunctionPlot[19].Y = 172.0

	pointsOfFunctionPlot[20].X = 2.0
	pointsOfFunctionPlot[20].Y = 736.0

	pointsOfFunctionPlot[21].X = 2.1
	pointsOfFunctionPlot[21].Y = 211.0

	pointsOfFunctionPlot[22].X = 2.2
	pointsOfFunctionPlot[22].Y = 368.0

	pointsOfFunctionPlot[23].X = 2.3
	pointsOfFunctionPlot[23].Y = 576.0

	pointsOfFunctionPlot[24].X = 2.4
	pointsOfFunctionPlot[24].Y = 429.0

	pointsOfFunctionPlot[25].X = 2.5
	pointsOfFunctionPlot[25].Y = 782.0

	pointsOfFunctionPlot[26].X = 2.6
	pointsOfFunctionPlot[26].Y = 530.0

	pointsOfFunctionPlot[27].X = 2.7
	pointsOfFunctionPlot[27].Y = 862.0

	pointsOfFunctionPlot[28].X = 2.8
	pointsOfFunctionPlot[28].Y = 123.0

	pointsOfFunctionPlot[29].X = 2.9
	pointsOfFunctionPlot[29].Y = 67.0

	pointsOfFunctionPlot[30].X = 3.0
	pointsOfFunctionPlot[30].Y = 135.0

	pointsOfFunctionPlot[31].X = 3.1
	pointsOfFunctionPlot[31].Y = 929.0

	pointsOfFunctionPlot[32].X = 3.2
	pointsOfFunctionPlot[32].Y = 802.0

	pointsOfFunctionPlot[33].X = 3.3
	pointsOfFunctionPlot[33].Y = 22.0

	pointsOfFunctionPlot[34].X = 3.4
	pointsOfFunctionPlot[34].Y = 58.0

	pointsOfFunctionPlot[35].X = 3.5
	pointsOfFunctionPlot[35].Y = 69.0

	pointsOfFunctionPlot[36].X = 3.6
	pointsOfFunctionPlot[36].Y = 167

	pointsOfFunctionPlot[37].X = 3.7
	pointsOfFunctionPlot[37].Y = 393.0

	pointsOfFunctionPlot[38].X = 3.8
	pointsOfFunctionPlot[38].Y = 456.0

	pointsOfFunctionPlot[39].X = 3.9
	pointsOfFunctionPlot[39].Y = 11.0

	pointsOfFunctionPlot[40].X = 4.0
	pointsOfFunctionPlot[40].Y = 42.0

	pointsOfFunctionPlot[41].X = 4.1
	pointsOfFunctionPlot[41].Y = 229.0

	pointsOfFunctionPlot[42].X = 4.2
	pointsOfFunctionPlot[42].Y = 373.0

	pointsOfFunctionPlot[43].X = 4.3
	pointsOfFunctionPlot[43].Y = 421.0

	pointsOfFunctionPlot[44].X = 4.4
	pointsOfFunctionPlot[44].Y = 919.0

	pointsOfFunctionPlot[45].X = 4.5
	pointsOfFunctionPlot[45].Y = 784.0

	pointsOfFunctionPlot[46].X = 4.6
	pointsOfFunctionPlot[46].Y = 537.0

	pointsOfFunctionPlot[47].X = 4.7
	pointsOfFunctionPlot[47].Y = 198.0

	pointsOfFunctionPlot[48].X = 4.8
	pointsOfFunctionPlot[48].Y = 324.0

	pointsOfFunctionPlot[49].X = 4.9
	pointsOfFunctionPlot[49].Y = 315.0

	pointsOfFunctionPlot[50].X = 5.0
	pointsOfFunctionPlot[50].Y = 370.0

	pointsOfFunctionPlot[51].X = 5.1
	pointsOfFunctionPlot[51].Y = 413.0

	pointsOfFunctionPlot[52].X = 5.2
	pointsOfFunctionPlot[52].Y = 526.0

	pointsOfFunctionPlot[53].X = 5.3
	pointsOfFunctionPlot[53].Y = 91.0

	pointsOfFunctionPlot[54].X = 5.4
	pointsOfFunctionPlot[54].Y = 980.0

	pointsOfFunctionPlot[55].X = 5.5
	pointsOfFunctionPlot[55].Y = 956.0

	pointsOfFunctionPlot[56].X = 5.6
	pointsOfFunctionPlot[56].Y = 873.0

	pointsOfFunctionPlot[57].X = 5.7
	pointsOfFunctionPlot[57].Y = 862.0

	pointsOfFunctionPlot[58].X = 5.8
	pointsOfFunctionPlot[58].Y = 170.0

	pointsOfFunctionPlot[59].X = 5.9
	pointsOfFunctionPlot[59].Y = 996.0

	pointsOfFunctionPlot[60].X = 6.0
	pointsOfFunctionPlot[60].Y = 281.0

	pointsOfFunctionPlot[61].X = 6.1
	pointsOfFunctionPlot[61].Y = 305.0

	pointsOfFunctionPlot[62].X = 6.2
	pointsOfFunctionPlot[62].Y = 925.0

	pointsOfFunctionPlot[63].X = 6.3
	pointsOfFunctionPlot[63].Y = 84.0

	pointsOfFunctionPlot[64].X = 6.4
	pointsOfFunctionPlot[64].Y = 327.0

	pointsOfFunctionPlot[65].X = 6.5
	pointsOfFunctionPlot[65].Y = 336.0

	pointsOfFunctionPlot[66].X = 6.6
	pointsOfFunctionPlot[66].Y = 505.0

	pointsOfFunctionPlot[67].X = 6.7
	pointsOfFunctionPlot[67].Y = 846.0

	pointsOfFunctionPlot[68].X = 6.8
	pointsOfFunctionPlot[68].Y = 729.0

	pointsOfFunctionPlot[69].X = 6.9
	pointsOfFunctionPlot[69].Y = 313.0

	pointsOfFunctionPlot[70].X = 7.0
	pointsOfFunctionPlot[70].Y = 857.0

	pointsOfFunctionPlot[71].X = 7.1
	pointsOfFunctionPlot[71].Y = 124.0

	pointsOfFunctionPlot[72].X = 7.2
	pointsOfFunctionPlot[72].Y = 895.0

	pointsOfFunctionPlot[73].X = 7.3
	pointsOfFunctionPlot[73].Y = 582.0

	pointsOfFunctionPlot[74].X = 7.4
	pointsOfFunctionPlot[74].Y = 545.0

	pointsOfFunctionPlot[75].X = 7.5
	pointsOfFunctionPlot[75].Y = 814.0

	pointsOfFunctionPlot[76].X = 7.6
	pointsOfFunctionPlot[76].Y = 367.0

	pointsOfFunctionPlot[77].X = 7.7
	pointsOfFunctionPlot[77].Y = 434.0

	pointsOfFunctionPlot[78].X = 7.8
	pointsOfFunctionPlot[78].Y = 364.0

	pointsOfFunctionPlot[79].X = 7.9
	pointsOfFunctionPlot[79].Y = 43.0

	pointsOfFunctionPlot[80].X = 8.0
	pointsOfFunctionPlot[80].Y = 750.0

	pointsOfFunctionPlot[81].X = 8.1
	pointsOfFunctionPlot[81].Y = 87.0

	pointsOfFunctionPlot[82].X = 8.2
	pointsOfFunctionPlot[82].Y = 808.0

	pointsOfFunctionPlot[83].X = 8.3
	pointsOfFunctionPlot[83].Y = 276.0

	pointsOfFunctionPlot[84].X = 8.4
	pointsOfFunctionPlot[84].Y = 178.0

	pointsOfFunctionPlot[85].X = 8.5
	pointsOfFunctionPlot[85].Y = 788.0

	pointsOfFunctionPlot[86].X = 8.6
	pointsOfFunctionPlot[86].Y = 584.0

	pointsOfFunctionPlot[87].X = 8.7
	pointsOfFunctionPlot[87].Y = 403.0

	pointsOfFunctionPlot[88].X = 8.8
	pointsOfFunctionPlot[88].Y = 651.0

	pointsOfFunctionPlot[89].X = 8.9
	pointsOfFunctionPlot[89].Y = 754.0

	pointsOfFunctionPlot[90].X = 9.0
	pointsOfFunctionPlot[90].Y = 399.0

	pointsOfFunctionPlot[91].X = 9.1
	pointsOfFunctionPlot[91].Y = 932.0

	pointsOfFunctionPlot[92].X = 9.2
	pointsOfFunctionPlot[92].Y = 60.0

	pointsOfFunctionPlot[93].X = 9.3
	pointsOfFunctionPlot[93].Y = 676.0

	pointsOfFunctionPlot[94].X = 9.4
	pointsOfFunctionPlot[94].Y = 368.0

	pointsOfFunctionPlot[95].X = 9.5
	pointsOfFunctionPlot[95].Y = 739.0

	pointsOfFunctionPlot[96].X = 9.6
	pointsOfFunctionPlot[96].Y = 12.0

	pointsOfFunctionPlot[97].X = 9.7
	pointsOfFunctionPlot[97].Y = 226.0

	pointsOfFunctionPlot[98].X = 9.8
	pointsOfFunctionPlot[98].Y = 586.0

	pointsOfFunctionPlot[99].X = 9.9
	pointsOfFunctionPlot[99].Y = 94.0

	pointsOfFunctionPlot[100].X = 10.0
	pointsOfFunctionPlot[100].Y = 539.0

	pointsOfFunctionPlot[101].X = 10.1
	pointsOfFunctionPlot[101].Y = 795.0

	pointsOfFunctionPlot[102].X = 10.2
	pointsOfFunctionPlot[102].Y = 570.0

	pointsOfFunctionPlot[103].X = 10.3
	pointsOfFunctionPlot[103].Y = 434.0

	pointsOfFunctionPlot[104].X = 10.4
	pointsOfFunctionPlot[104].Y = 378.0

	pointsOfFunctionPlot[105].X = 10.5
	pointsOfFunctionPlot[105].Y = 467.0

	pointsOfFunctionPlot[106].X = 10.6
	pointsOfFunctionPlot[106].Y = 601.0

	pointsOfFunctionPlot[107].X = 10.7
	pointsOfFunctionPlot[107].Y = 97.0

	pointsOfFunctionPlot[108].X = 10.8
	pointsOfFunctionPlot[108].Y = 902.0

	pointsOfFunctionPlot[109].X = 10.9
	pointsOfFunctionPlot[109].Y = 317.0

	pointsOfFunctionPlot[110].X = 11.0
	pointsOfFunctionPlot[110].Y = 492.0

	pointsOfFunctionPlot[111].X = 11.1
	pointsOfFunctionPlot[111].Y = 652.0

	pointsOfFunctionPlot[112].X = 11.2
	pointsOfFunctionPlot[112].Y = 756.0

	pointsOfFunctionPlot[113].X = 11.3
	pointsOfFunctionPlot[113].Y = 301.0

	pointsOfFunctionPlot[114].X = 11.4
	pointsOfFunctionPlot[114].Y = 280.0

	pointsOfFunctionPlot[115].X = 11.5
	pointsOfFunctionPlot[115].Y = 286.0

	pointsOfFunctionPlot[116].X = 11.6
	pointsOfFunctionPlot[116].Y = 441.0

	pointsOfFunctionPlot[117].X = 11.7
	pointsOfFunctionPlot[117].Y = 865.0

	pointsOfFunctionPlot[118].X = 11.8
	pointsOfFunctionPlot[118].Y = 689.0

	pointsOfFunctionPlot[119].X = 11.9
	pointsOfFunctionPlot[119].Y = 444.0

	pointsOfFunctionPlot[120].X = 12.0
	pointsOfFunctionPlot[120].Y = 619.0

	pointsOfFunctionPlot[121].X = 12.1
	pointsOfFunctionPlot[121].Y = 440.0

	pointsOfFunctionPlot[122].X = 12.2
	pointsOfFunctionPlot[122].Y = 729.0

	pointsOfFunctionPlot[123].X = 12.3
	pointsOfFunctionPlot[123].Y = 31.0

	pointsOfFunctionPlot[124].X = 12.4
	pointsOfFunctionPlot[124].Y = 117.0

	pointsOfFunctionPlot[125].X = 12.5
	pointsOfFunctionPlot[125].Y = 97.0

	pointsOfFunctionPlot[126].X = 12.6
	pointsOfFunctionPlot[126].Y = 771.0

	pointsOfFunctionPlot[127].X = 12.7
	pointsOfFunctionPlot[127].Y = 481.0

	pointsOfFunctionPlot[128].X = 12.8
	pointsOfFunctionPlot[128].Y = 675.0

	pointsOfFunctionPlot[129].X = 12.9
	pointsOfFunctionPlot[129].Y = 709.0

	pointsOfFunctionPlot[130].X = 13.0
	pointsOfFunctionPlot[130].Y = 927.0

	pointsOfFunctionPlot[131].X = 13.1
	pointsOfFunctionPlot[131].Y = 567.0

	pointsOfFunctionPlot[132].X = 13.2
	pointsOfFunctionPlot[132].Y = 856.0

	pointsOfFunctionPlot[133].X = 13.3
	pointsOfFunctionPlot[133].Y = 497.0

	pointsOfFunctionPlot[134].X = 13.4
	pointsOfFunctionPlot[134].Y = 353.0

	pointsOfFunctionPlot[135].X = 13.5
	pointsOfFunctionPlot[135].Y = 586.0

	pointsOfFunctionPlot[136].X = 13.6
	pointsOfFunctionPlot[136].Y = 965.0

	pointsOfFunctionPlot[137].X = 13.7
	pointsOfFunctionPlot[137].Y = 306.0

	pointsOfFunctionPlot[138].X = 13.8
	pointsOfFunctionPlot[138].Y = 683.0

	pointsOfFunctionPlot[139].X = 13.9
	pointsOfFunctionPlot[139].Y = 219.0

	pointsOfFunctionPlot[140].X = 14.0
	pointsOfFunctionPlot[140].Y = 624.0

	pointsOfFunctionPlot[141].X = 14.1
	pointsOfFunctionPlot[141].Y = 528.0

	pointsOfFunctionPlot[142].X = 14.2
	pointsOfFunctionPlot[142].Y = 871.0

	pointsOfFunctionPlot[143].X = 14.3
	pointsOfFunctionPlot[143].Y = 732.0

	pointsOfFunctionPlot[144].X = 14.4
	pointsOfFunctionPlot[144].Y = 829.0

	pointsOfFunctionPlot[145].X = 14.5
	pointsOfFunctionPlot[145].Y = 503.0

	pointsOfFunctionPlot[146].X = 14.6
	pointsOfFunctionPlot[146].Y = 19.0

	pointsOfFunctionPlot[147].X = 14.7
	pointsOfFunctionPlot[147].Y = 270.0

	pointsOfFunctionPlot[148].X = 14.8
	pointsOfFunctionPlot[148].Y = 368.0

	pointsOfFunctionPlot[149].X = 14.9
	pointsOfFunctionPlot[149].Y = 708.0

	pointsOfFunctionPlot[150].X = 15.0
	pointsOfFunctionPlot[150].Y = 715.0

	pointsOfFunctionPlot[151].X = 15.1
	pointsOfFunctionPlot[151].Y = 340.0

	pointsOfFunctionPlot[152].X = 15.2
	pointsOfFunctionPlot[152].Y = 149.0

	pointsOfFunctionPlot[153].X = 15.3
	pointsOfFunctionPlot[153].Y = 796.0

	pointsOfFunctionPlot[154].X = 15.4
	pointsOfFunctionPlot[154].Y = 723.0

	pointsOfFunctionPlot[155].X = 15.5
	pointsOfFunctionPlot[155].Y = 618.0

	pointsOfFunctionPlot[156].X = 15.6
	pointsOfFunctionPlot[156].Y = 245.0

	pointsOfFunctionPlot[157].X = 15.7
	pointsOfFunctionPlot[157].Y = 846.0

	pointsOfFunctionPlot[158].X = 15.8
	pointsOfFunctionPlot[158].Y = 451.0

	pointsOfFunctionPlot[159].X = 15.9
	pointsOfFunctionPlot[159].Y = 921.0

	pointsOfFunctionPlot[160].X = 16.0
	pointsOfFunctionPlot[160].Y = 555.0

	pointsOfFunctionPlot[161].X = 16.1
	pointsOfFunctionPlot[161].Y = 379.0

	pointsOfFunctionPlot[162].X = 16.2
	pointsOfFunctionPlot[162].Y = 488.0

	pointsOfFunctionPlot[163].X = 16.3
	pointsOfFunctionPlot[163].Y = 764.0

	pointsOfFunctionPlot[164].X = 16.4
	pointsOfFunctionPlot[164].Y = 228.0

	pointsOfFunctionPlot[165].X = 16.5
	pointsOfFunctionPlot[165].Y = 841.0

	pointsOfFunctionPlot[166].X = 16.6
	pointsOfFunctionPlot[166].Y = 350.0

	pointsOfFunctionPlot[167].X = 16.7
	pointsOfFunctionPlot[167].Y = 193.0

	pointsOfFunctionPlot[168].X = 16.8
	pointsOfFunctionPlot[168].Y = 500.0

	pointsOfFunctionPlot[169].X = 16.9
	pointsOfFunctionPlot[169].Y = 34.0

	pointsOfFunctionPlot[170].X = 17.0
	pointsOfFunctionPlot[170].Y = 764.0

	pointsOfFunctionPlot[171].X = 17.1
	pointsOfFunctionPlot[171].Y = 124.0

	pointsOfFunctionPlot[172].X = 17.2
	pointsOfFunctionPlot[172].Y = 914.0

	pointsOfFunctionPlot[173].X = 17.3
	pointsOfFunctionPlot[173].Y = 987.0

	pointsOfFunctionPlot[174].X = 17.4
	pointsOfFunctionPlot[174].Y = 856.0

	pointsOfFunctionPlot[175].X = 17.5
	pointsOfFunctionPlot[175].Y = 743.0

	pointsOfFunctionPlot[176].X = 17.6
	pointsOfFunctionPlot[176].Y = 491.0

	pointsOfFunctionPlot[177].X = 17.7
	pointsOfFunctionPlot[177].Y = 227.0

	pointsOfFunctionPlot[178].X = 17.8
	pointsOfFunctionPlot[178].Y = 365.0

	pointsOfFunctionPlot[179].X = 17.9
	pointsOfFunctionPlot[179].Y = 859.0

	pointsOfFunctionPlot[180].X = 18.0
	pointsOfFunctionPlot[180].Y = 936.0

	pointsOfFunctionPlot[181].X = 18.1
	pointsOfFunctionPlot[181].Y = 432.0

	pointsOfFunctionPlot[182].X = 18.2
	pointsOfFunctionPlot[182].Y = 551.0

	pointsOfFunctionPlot[183].X = 18.3
	pointsOfFunctionPlot[183].Y = 437.0

	pointsOfFunctionPlot[184].X = 18.4
	pointsOfFunctionPlot[184].Y = 228.0

	pointsOfFunctionPlot[185].X = 18.5
	pointsOfFunctionPlot[185].Y = 275.0

	pointsOfFunctionPlot[186].X = 18.6
	pointsOfFunctionPlot[186].Y = 407.0

	pointsOfFunctionPlot[187].X = 18.7
	pointsOfFunctionPlot[187].Y = 474.0

	pointsOfFunctionPlot[188].X = 18.8
	pointsOfFunctionPlot[188].Y = 121.0

	pointsOfFunctionPlot[189].X = 18.9
	pointsOfFunctionPlot[189].Y = 858.0

	pointsOfFunctionPlot[190].X = 19.0
	pointsOfFunctionPlot[190].Y = 395.0

	pointsOfFunctionPlot[191].X = 19.1
	pointsOfFunctionPlot[191].Y = 29.0

	pointsOfFunctionPlot[192].X = 19.2
	pointsOfFunctionPlot[192].Y = 237.0

	pointsOfFunctionPlot[193].X = 19.3
	pointsOfFunctionPlot[193].Y = 235.0

	pointsOfFunctionPlot[194].X = 19.4
	pointsOfFunctionPlot[194].Y = 793.0

	pointsOfFunctionPlot[195].X = 19.5
	pointsOfFunctionPlot[195].Y = 818.0

	pointsOfFunctionPlot[196].X = 19.6
	pointsOfFunctionPlot[196].Y = 428.0

	pointsOfFunctionPlot[197].X = 19.7
	pointsOfFunctionPlot[197].Y = 143.0

	pointsOfFunctionPlot[198].X = 19.8
	pointsOfFunctionPlot[198].Y = 11.0

	pointsOfFunctionPlot[199].X = 19.9
	pointsOfFunctionPlot[199].Y = 928.0

	pointsOfFunctionPlot[200].X = 20.0
	pointsOfFunctionPlot[200].Y = 529.0

	pointsOfFunctionPlot[201].X = 20.1
	pointsOfFunctionPlot[201].Y = 776.0

	pointsOfFunctionPlot[202].X = 20.2
	pointsOfFunctionPlot[202].Y = 404.0

	pointsOfFunctionPlot[203].X = 20.3
	pointsOfFunctionPlot[203].Y = 443.0

	pointsOfFunctionPlot[204].X = 20.4
	pointsOfFunctionPlot[204].Y = 763.0

	pointsOfFunctionPlot[205].X = 20.5
	pointsOfFunctionPlot[205].Y = 613.0

	pointsOfFunctionPlot[206].X = 20.6
	pointsOfFunctionPlot[206].Y = 538.0

	pointsOfFunctionPlot[207].X = 20.7
	pointsOfFunctionPlot[207].Y = 606.0

	pointsOfFunctionPlot[208].X = 20.8
	pointsOfFunctionPlot[208].Y = 840.0

	pointsOfFunctionPlot[209].X = 20.9
	pointsOfFunctionPlot[209].Y = 904.0

	pointsOfFunctionPlot[210].X = 21.0
	pointsOfFunctionPlot[210].Y = 818.0

	pointsOfFunctionPlot[211].X = 21.1
	pointsOfFunctionPlot[211].Y = 128.0

	pointsOfFunctionPlot[212].X = 21.2
	pointsOfFunctionPlot[212].Y = 688.0

	pointsOfFunctionPlot[213].X = 21.3
	pointsOfFunctionPlot[213].Y = 369.0

	pointsOfFunctionPlot[214].X = 21.4
	pointsOfFunctionPlot[214].Y = 917.0

	pointsOfFunctionPlot[215].X = 21.5
	pointsOfFunctionPlot[215].Y = 917.0

	pointsOfFunctionPlot[216].X = 21.6
	pointsOfFunctionPlot[216].Y = 996.0

	pointsOfFunctionPlot[217].X = 21.7
	pointsOfFunctionPlot[217].Y = 324.0

	pointsOfFunctionPlot[218].X = 21.8
	pointsOfFunctionPlot[218].Y = 743.0

	pointsOfFunctionPlot[219].X = 21.9
	pointsOfFunctionPlot[219].Y = 470.0

	pointsOfFunctionPlot[220].X = 22.0
	pointsOfFunctionPlot[220].Y = 183.0

	pointsOfFunctionPlot[221].X = 22.1
	pointsOfFunctionPlot[221].Y = 490.0

	pointsOfFunctionPlot[222].X = 22.2
	pointsOfFunctionPlot[222].Y = 499.0

	pointsOfFunctionPlot[223].X = 22.3
	pointsOfFunctionPlot[223].Y = 772.0

	pointsOfFunctionPlot[224].X = 22.4
	pointsOfFunctionPlot[224].Y = 725.0

	pointsOfFunctionPlot[225].X = 22.5
	pointsOfFunctionPlot[225].Y = 644.0

	pointsOfFunctionPlot[226].X = 22.6
	pointsOfFunctionPlot[226].Y = 505.0

	pointsOfFunctionPlot[227].X = 22.7
	pointsOfFunctionPlot[227].Y = 505.0

	pointsOfFunctionPlot[228].X = 22.8
	pointsOfFunctionPlot[228].Y = 139.0

	pointsOfFunctionPlot[229].X = 22.9
	pointsOfFunctionPlot[229].Y = 954.0

	pointsOfFunctionPlot[230].X = 23.0
	pointsOfFunctionPlot[230].Y = 786.0

	pointsOfFunctionPlot[231].X = 23.1
	pointsOfFunctionPlot[231].Y = 669.0

	pointsOfFunctionPlot[232].X = 23.2
	pointsOfFunctionPlot[232].Y = 82.0

	pointsOfFunctionPlot[233].X = 23.3
	pointsOfFunctionPlot[233].Y = 542.0

	pointsOfFunctionPlot[234].X = 23.4
	pointsOfFunctionPlot[234].Y = 464.0

	pointsOfFunctionPlot[235].X = 23.5
	pointsOfFunctionPlot[235].Y = 197.0

	pointsOfFunctionPlot[236].X = 23.6
	pointsOfFunctionPlot[236].Y = 507.0

	pointsOfFunctionPlot[237].X = 23.7
	pointsOfFunctionPlot[237].Y = 355.0

	pointsOfFunctionPlot[238].X = 23.8
	pointsOfFunctionPlot[238].Y = 804.0

	pointsOfFunctionPlot[239].X = 23.9
	pointsOfFunctionPlot[239].Y = 348.0

	pointsOfFunctionPlot[240].X = 24.0
	pointsOfFunctionPlot[240].Y = 611.0

	pointsOfFunctionPlot[241].X = 24.1
	pointsOfFunctionPlot[241].Y = 622.0

	pointsOfFunctionPlot[242].X = 24.2
	pointsOfFunctionPlot[242].Y = 828

	pointsOfFunctionPlot[243].X = 24.3
	pointsOfFunctionPlot[243].Y = 299.0

	pointsOfFunctionPlot[244].X = 24.4
	pointsOfFunctionPlot[244].Y = 343.0

	pointsOfFunctionPlot[245].X = 24.5
	pointsOfFunctionPlot[245].Y = 746.0

	pointsOfFunctionPlot[246].X = 24.6
	pointsOfFunctionPlot[246].Y = 568.0

	pointsOfFunctionPlot[247].X = 24.7
	pointsOfFunctionPlot[247].Y = 340.0

	pointsOfFunctionPlot[248].X = 24.8
	pointsOfFunctionPlot[248].Y = 422.0

	pointsOfFunctionPlot[249].X = 24.9
	pointsOfFunctionPlot[249].Y = 311.0

	pointsOfFunctionPlot[250].X = 25.0
	pointsOfFunctionPlot[250].Y = 810.0

	pointsOfFunctionPlot[251].X = 25.1
	pointsOfFunctionPlot[251].Y = 605.0

	pointsOfFunctionPlot[252].X = 25.2
	pointsOfFunctionPlot[252].Y = 801.0

	pointsOfFunctionPlot[253].X = 25.3
	pointsOfFunctionPlot[253].Y = 661.0

	pointsOfFunctionPlot[254].X = 25.4
	pointsOfFunctionPlot[254].Y = 730.0

	pointsOfFunctionPlot[255].X = 25.5
	pointsOfFunctionPlot[255].Y = 878.0

	pointsOfFunctionPlot[256].X = 25.6
	pointsOfFunctionPlot[256].Y = 305.0

	pointsOfFunctionPlot[257].X = 25.7
	pointsOfFunctionPlot[257].Y = 320.0

	pointsOfFunctionPlot[258].X = 25.8
	pointsOfFunctionPlot[258].Y = 736.0

	pointsOfFunctionPlot[259].X = 25.9
	pointsOfFunctionPlot[259].Y = 444.0

	pointsOfFunctionPlot[260].X = 26.0
	pointsOfFunctionPlot[260].Y = 626.0

	pointsOfFunctionPlot[261].X = 26.1
	pointsOfFunctionPlot[261].Y = 522.0

	pointsOfFunctionPlot[262].X = 26.2
	pointsOfFunctionPlot[262].Y = 465.0

	pointsOfFunctionPlot[263].X = 26.3
	pointsOfFunctionPlot[263].Y = 708.0

	pointsOfFunctionPlot[264].X = 26.4
	pointsOfFunctionPlot[264].Y = 416.0

	pointsOfFunctionPlot[265].X = 26.5
	pointsOfFunctionPlot[265].Y = 282.0

	pointsOfFunctionPlot[266].X = 26.6
	pointsOfFunctionPlot[266].Y = 258.0

	pointsOfFunctionPlot[267].X = 26.7
	pointsOfFunctionPlot[267].Y = 924.0

	pointsOfFunctionPlot[268].X = 26.8
	pointsOfFunctionPlot[268].Y = 637.0

	pointsOfFunctionPlot[269].X = 26.9
	pointsOfFunctionPlot[269].Y = 62.0

	pointsOfFunctionPlot[270].X = 27.0
	pointsOfFunctionPlot[270].Y = 624.0

	pointsOfFunctionPlot[271].X = 27.1
	pointsOfFunctionPlot[271].Y = 600.0

	pointsOfFunctionPlot[272].X = 27.2
	pointsOfFunctionPlot[272].Y = 36.0

	pointsOfFunctionPlot[273].X = 27.3
	pointsOfFunctionPlot[273].Y = 452.0

	pointsOfFunctionPlot[274].X = 27.4
	pointsOfFunctionPlot[274].Y = 899.0

	pointsOfFunctionPlot[275].X = 27.5
	pointsOfFunctionPlot[275].Y = 379.0

	pointsOfFunctionPlot[276].X = 27.6
	pointsOfFunctionPlot[276].Y = 550.0

	pointsOfFunctionPlot[277].X = 27.7
	pointsOfFunctionPlot[277].Y = 468.0

	pointsOfFunctionPlot[278].X = 27.8
	pointsOfFunctionPlot[278].Y = 71.0

	pointsOfFunctionPlot[279].X = 27.9
	pointsOfFunctionPlot[279].Y = 973.0

	pointsOfFunctionPlot[280].X = 28.0
	pointsOfFunctionPlot[280].Y = 131.0

	pointsOfFunctionPlot[281].X = 28.1
	pointsOfFunctionPlot[281].Y = 881.0

	pointsOfFunctionPlot[282].X = 28.2
	pointsOfFunctionPlot[282].Y = 930.0

	pointsOfFunctionPlot[283].X = 28.3
	pointsOfFunctionPlot[283].Y = 933.0

	pointsOfFunctionPlot[284].X = 28.4
	pointsOfFunctionPlot[284].Y = 894.0

	pointsOfFunctionPlot[285].X = 28.5
	pointsOfFunctionPlot[285].Y = 660.0

	pointsOfFunctionPlot[286].X = 28.6
	pointsOfFunctionPlot[286].Y = 163.0

	pointsOfFunctionPlot[287].X = 28.7
	pointsOfFunctionPlot[287].Y = 199.0

	pointsOfFunctionPlot[288].X = 28.8
	pointsOfFunctionPlot[288].Y = 981.0

	pointsOfFunctionPlot[289].X = 28.9
	pointsOfFunctionPlot[289].Y = 899.0

	pointsOfFunctionPlot[290].X = 29.0
	pointsOfFunctionPlot[290].Y = 996.0

	pointsOfFunctionPlot[291].X = 29.1
	pointsOfFunctionPlot[291].Y = 959.0

	pointsOfFunctionPlot[292].X = 29.2
	pointsOfFunctionPlot[292].Y = 773.0

	pointsOfFunctionPlot[293].X = 29.3
	pointsOfFunctionPlot[293].Y = 813.0

	pointsOfFunctionPlot[294].X = 29.4
	pointsOfFunctionPlot[294].Y = 668.0

	pointsOfFunctionPlot[295].X = 29.5
	pointsOfFunctionPlot[295].Y = 190.0

	pointsOfFunctionPlot[296].X = 29.6
	pointsOfFunctionPlot[296].Y = 95.0

	pointsOfFunctionPlot[297].X = 29.7
	pointsOfFunctionPlot[297].Y = 926.0

	pointsOfFunctionPlot[298].X = 29.8
	pointsOfFunctionPlot[298].Y = 466.0

	pointsOfFunctionPlot[299].X = 29.9
	pointsOfFunctionPlot[299].Y = 84.0

	pointsOfFunctionPlot[300].X = 30.0
	pointsOfFunctionPlot[300].Y = 340.0










	plotOfFunction := plot.New()

	plotOfFunction.Title.Text = "Plot of pseudorandom integers"

	plotOfFunction.X.Label.Text = "x"
	plotOfFunction.Y.Label.Text = "y"

	plotLine, err := plotter.NewLine(pointsOfFunctionPlot)

	if err != nil {
		panic(err)
	}

	plotLine.LineStyle.Width = vg.Points(0.1)
	plotLine.Color = color.RGBA{R: 200, G: 100, B: 100}

	plotOfFunction.Add(plotLine)
	plotOfFunction.Legend.Add("pseudorandom integers", plotLine)

	if err := plotOfFunction.Save(10*vg.Inch, 10*vg.Inch,
		"random-integers-plot-01.png"); err != nil {

		panic(err)
	}
}
